### ISSUE TITLE
Please update readme.md to include instructions for running on windows

### ISSUE THREAD

**Issue by MayurVirkar** [reworkd/AgentGPT#148]
Title says everything :)
Thanks

**Comment by exilvm** [comment]
Hello! Have you checked the [Manual Setup](https://github.com/reworkd/AgentGPT#%EF%B8%8F-manual-setup) section in README file?
It provides a step-by-step guide that is cross-platform compatible and should work on Windows as well.

Additionally, if you don't have Git installed, you can download the repository source as a zip file instead of cloning it.

**Comment by yourepicservices** [comment]
Hi, @MayurVirkar. What is unclear about running on Windows in the documentation? If the node.js dependency is installed, you should be able to follow the instructions provided in the readme.md for installation and running in a Windows environment.

**Comment by asim-shrestha** [comment]
Hey @MayurVirkar, so our CLI should work on windows as well. Would you be cool with porting our `setup.sh` to windows? (All it does is run npm install, npm run build)

**Comment by jasangill1** [comment]
updated install guide !!
