### ISSUE TITLE
update instructions to say how to start the app after docker install

### ISSUE THREAD

**Issue by mowliv** [reworkd/AgentGPT#189]
I did the docker install, worked great. But how do I start the app and use it? Maybe I'm missing something... I recommend adding that info to the instructions.

**Comment by exilvm** [comment]
The Dockerfile exposes port `3000` and the `docker run` command binds it to your localhost on port [`3000`](https://github.com/reworkd/AgentGPT/blob/60adcff47dee1c7870b5b71c9ceb17ff965914df/setup.sh#L21).

So the app should be accesible at: `localhost:3000`.

**Comment by mowliv** [comment]
Thanks. With ChatGPT's help I figured out the magic command:

`docker run agentgpt`

**Comment by exilvm** [comment]
Good! Also check the [Getting Started](https://github.com/reworkd/AgentGPT#-getting-started) section if you didnt.

**Comment by mowliv** [comment]
Yes, that's where I started. That's why I opened this ticket. That one
extra command should be added to the docker start section.

**Comment by yourepicservices** [comment]
Task:

- [ ] Add docker command to documentation "docker run agentgpt"

**Comment by asim-shrestha** [comment]
We've since updated our setup scripts from this time and actually removed guidance for `docker` alone. This is because running through docker compose will deal with managing all of the sub-services which is especially important now as we integrate with things like a VectorDB.

Thanks for the help here folks!
