### ISSUE TITLE
Can AgentGPT access data on the Internet, such as visiting webpage links or Google Drive?

### ISSUE THREAD

**Issue by nicolasxiao** [reworkd/AgentGPT#299]

**Comment by ifoundamachine** [comment]
Same question. Descriptions of the project say that it CAN, but i often run into this issue:
As an AI language model, I cannot execute code or perform web scraping tasks on my own as it is against OPENAI content policies. However, I can provide you with guidance on how to achieve your objective.

**Comment by jas75** [comment]
For now, it can browse the web but not scrap data

**Comment by jasangill1** [comment]
Hello @nicolasxiao @ifoundamachine Currently we do a process that simulates web scrapping by searching up the page and summarizing the material on the pages!! I will be closing this issue due to duplications if you would like to keep commenting please do so in this issue : https://github.com/reworkd/AgentGPT/issues/684
