### ISSUE TITLE
NextJs can't handle highlighting code when dealing with the solidity language

### ISSUE THREAD

**Issue by gluneau** [reworkd/AgentGPT#352]
Unless you can find the solidity highlighter, override and just use javascript highlights.

```
Error: Unknown language: `solidity` is not registered
    at t (614-3ca9223a1d03c23a.js:29:235463)
    at Object.ew [as highlight] (614-3ca9223a1d03c23a.js:29:235647)
    at 614-3ca9223a1d03c23a.js:29:343426
    at 614-3ca9223a1d03c23a.js:29:406638
    at node (element<code>) (614-3ca9223a1d03c23a.js:29:406153)
    at node (element<pre>) (614-3ca9223a1d03c23a.js:29:406341)
    at node (root) (614-3ca9223a1d03c23a.js:29:406341)
    at i (614-3ca9223a1d03c23a.js:29:406414)
    at i (614-3ca9223a1d03c23a.js:29:406592)
    at 614-3ca9223a1d03c23a.js:29:342849
K @ main-c4338cbacf51f33e.js:1
main-c4338cbacf51f33e.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-c4338cbacf51f33e.js:1
```

**Comment by yourepicservices** [comment]
Is this something you'd be interested in working on?

**Comment by gluneau** [comment]
Sure @yourepicservices, assign it to me, I'll work on it.

**Comment by asim-shrestha** [comment]
Ah just fixed this literally just now: https://github.com/reworkd/AgentGPT/commit/56777bbc034b00e84028fa13008b40740c11b173

The issue is Rehype does not have support for all languages (Like solidity) and will cause the above error when it must render it. The commit I submitted just ignores those highlighting for those langauges. 

We could alternatively supply our own highlighting if you're up to do that. (But I'm not sure the specifics myself)
