### ISSUE TITLE
🐛 Can directly modify the configuration from localStorage

### ISSUE THREAD

**Issue by Dogtiti** [reworkd/AgentGPT#428]
First, I entered a key and saved it to store the configuration in localStorage. Then, in the control panel, I removed the API key and refreshed the page to make it effective. At this point, I didn’t use my own API key, but I also modified the configuration.
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/38354472/235475055-8f0ff968-7eec-42fb-90fe-3f9286794144.png">
<img width="662" alt="image" src="https://user-images.githubusercontent.com/38354472/235475569-702221ce-d758-4887-91af-de21d554a0ca.png">

**Comment by asim-shrestha** [comment]
Hey yeah, we only want to accept custom settings if a custom API key is provided. For the frontend this doesn't really matter since users will always be able to get through these blockades. For the backend though, it looks we didn't properly check for this. Just fixed the code and added the below tests: 

https://github.com/reworkd/AgentGPT/commit/3dc8e4691d098c44ca0edd0ac70e6a1a331b7568
