### ISSUE TITLE
Login function is abnormal

### ISSUE THREAD

**Issue by linghongli** [reworkd/AgentGPT#472]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

Login function is normal

### Current behaviour

How does the interface look like this when I click to log in? Unable to log in normally, was it a third-party social platform login option before?
![123](https://user-images.githubusercontent.com/2770205/236776292-d0dbc70f-ffbe-476d-94f5-49a863a695ce.png)
![222](https://user-images.githubusercontent.com/2770205/236786386-291642dd-4345-42ef-9820-1f7c992efac3.png)

### Steps to reproduce

Click to log in

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by awtkns** [comment]
Hi @linghongli we recently added this so that people developing locally could have an easier time getting up and going. If you would like to switch back to provider based authentication please set the environment variable `NEXT_PUBLIC_VERCEL_ENV' to `production'.

It looks like you are also having issues with your database. This can be fixed with:
```
prisma generate
prisma db push
```
