### ISSUE TITLE
openai response for "completing" exceeds the amount of characters to be handled in output window

### ISSUE THREAD

**Issue by larsihasi** [reworkd/AgentGPT#473]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

response from openai should be fully visible in output window "completed"

### Current behaviour

Output is truncated after some amount of characters. This is observed using gpt-4 in German language.
<img width="1012" alt="agentgpt_error" src="https://user-images.githubusercontent.com/28692324/236780296-c14f8e04-ce0a-49f5-94ed-c66a13be98c1.png">

### Steps to reproduce

1. use any goal in German and use gpt-4 model. This is 100% reproducible for me

### Possible solution

maybe just output character size can be increased?

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by asim-shrestha** [comment]
Thanks @larsihasi, the issue is that the OpenAI models can only output a certain number of tokens (Each token will cost some money). If you provide your own API key, you are able to increase the token usage in the advanced settings 

![image](https://github.com/reworkd/AgentGPT/assets/50181239/3f2dcbed-d7f7-4e7b-bb13-be0143edfd1d)


See the botttom ^
