### ISSUE TITLE
This agent has been running for too long (25 Loops)

### ISSUE THREAD

**Issue by uozveren** [reworkd/AgentGPT#83]
The number of iterations should be configurable. How can I change it manually (At least it would be 100 Loops)?

**Comment by astelmach01** [comment]
#26

**Comment by skyecx** [comment]
可以在设置中设置loop的次数

**Comment by asim-shrestha** [comment]
Hey, we have added an option in the settings menu (Given you provide your own API key) to update this to 100 loops.

![image](https://user-images.githubusercontent.com/50181239/236127736-9d75dce5-4fa4-4bb7-a2f2-20659a4ebf52.png)

**Comment by amosref** [comment]
> 

unfortunately, even 100 loops are sometimes not enough, as the engine creates many instances of the exact same sub task. In my only attempt to use agentGPT, it probably created the same subtask about 10 times before running out of loops and "protecting my wallet". Used in GPT 3.5 because I am still (*sigh*) waiting for GPT4... :(

**Comment by trumanhung** [comment]
You can easily change the max value, just search the max value (which is 25 now) and replace it with the desired number.
