### ISSUE TITLE
No such file or directory source issue

### ISSUE THREAD

**Issue by bitcoinmeetups** [reworkd/AgentGPT#871]
Hi,

I'm Mr. PeakP, a very friendly guy. Got some issue here:

4> export PATH="/usr/local/bin:$PATH"
4> sudo docker compose run --rm auto-gpt
[+] Building 0.0s (0/0)
[+] Building 0.0s (0/0)
exec /usr/local/bin/python: no such file or directory
4>

Any ideas? Python is already installed.

**Comment by jasangill1** [comment]
Hello @bitcoinmeetups Not sure if you are meaning to say agentgpt instead of autogpt, If this is for autoGPt please post in their forms, if you need help installing please try the new installation guide here https://github.com/reworkd/AgentGPT.

Please let me know if this solves your problem if not feel free to shoot me a message always here to help

**Comment by bitcoinmeetups** [comment]
Nice. Yes, that was for Auto-GPT. However, seeing that you're nice, let me ask you if there is a terminal version of agent-gpt or if you could kindly make one. I prefer using the terminal over the browser.

**Comment by jasangill1** [comment]
Hello @bitcoinmeetups if u mean a local version of the product then yes there is just follow the download guide that was sent in the first comment !!!
